name: "Check stale for specific labels"
on:

  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: 'enhancement,good first issue'
