name: issue1029
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: gowridurgad/setup-node@main
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install
    
