name: versions

on:
  workflow_dispatch:
jobs:
  local-cache:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node

        with:
          node-version: ${{ matrix.node-version }}
      - name: Use node
        run: |
          node --version

  lts-syntax:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
      
        node-version: [lts/dubnium, lts/erbium, lts/fermium, lts/*, lts/-1]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
       
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - if: runner.os != 'Windows' && runner.os != 'macOS'
        name: Verify node and npm
        run: |
          . "$NVM_DIR/nvm.sh"
          [[ $(nvm version-remote "${{ matrix.node-version }}") =~ ^v([^.]+) ]]
          __tests__/verify-node.sh "${BASH_REMATCH[1]}"
        shell: bash

      - name: Use node
        run: |
          node --version
