name: PRtesting
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: fulldecent/setup-node@patch-1
        with:
          node-version: 'lts'
      - name: Install dependencies
        run: yarn install
