name: testingissue852
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Environment Variables
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "github.action_path = ${{ github.action_path }}"
    
    - uses: actions/checkout@v4

    - name: Debug Action Path
      run: |
        echo "GitHub Action Path: ${{ github.action_path }}"
        echo "Looking for .nvmrc at: ${{ github.action_path }}/.nvmrc"
        ls -l ${{ github.action_path }}
    
    - name: Set up Node.js
      uses: aparnajyothi-y/setup-node@use-absolute-path
      with:
        node-version-file: ${{ github.action_path }}/.nvmrc
