name: testingissue852
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gowridurgad/test-setup-node@main
      with:
         node-version-file: ${{ github.action_path }}/.nvmrc
        
     
