name: testingissue852
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Environment Variables
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "github.action_path = ${{ github.action_path }}"
    
    - uses: actions/checkout@v4

    - name: Run Composite Action Example
      uses: ./.github/actions/composite-action  # This is where you invoke the composite action
    
    - name: Set up Node.js
      uses: aparnajyothi-y/setup-node@use-absolute-path
      with:
        node-version-file: ${{ github.workspace }}/.github/actions/composite-action/.nvmrc
